/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as BuyerCartRouteImport } from './routes/buyer/cart'
import { Route as BuyerDashboardRouteImport } from './routes/buyer/dashboard'
import { Route as BuyerOrdersRouteImport } from './routes/buyer/orders'
import { Route as FarmerDashboardRouteImport } from './routes/farmer/dashboard'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceProductIdRouteImport } from './routes/marketplace/$productId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as FarmerProductsIndexRouteImport } from './routes/farmer/products/index'
import { Route as FarmerProductsProductIdRouteImport } from './routes/farmer/products/$productId'
import { Route as FarmerProductsNewRouteImport } from './routes/farmer/products/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerCartRoute = BuyerCartRouteImport.update({
  id: '/buyer/cart',
  path: '/buyer/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer/dashboard',
  path: '/buyer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/buyer/orders',
  path: '/buyer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/farmer/dashboard',
  path: '/farmer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProductIdRoute = MarketplaceProductIdRouteImport.update({
  id: '/marketplace/$productId',
  path: '/marketplace/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProductsIndexRoute = FarmerProductsIndexRouteImport.update({
  id: '/farmer/products/',
  path: '/farmer/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProductsProductIdRoute = FarmerProductsProductIdRouteImport.update({
  id: '/farmer/products/$productId',
  path: '/farmer/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProductsNewRoute = FarmerProductsNewRouteImport.update({
  id: '/farmer/products/new',
  path: '/farmer/products/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/farmer/products/$productId': typeof FarmerProductsProductIdRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/products/': typeof FarmerProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/farmer/products/$productId': typeof FarmerProductsProductIdRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/products': typeof FarmerProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/farmer/products/$productId': typeof FarmerProductsProductIdRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/products/': typeof FarmerProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/buyer/cart'
    | '/buyer/dashboard'
    | '/buyer/orders'
    | '/farmer/dashboard'
    | '/marketplace/$productId'
    | '/marketplace/'
    | '/api/auth/$'
    | '/farmer/products/$productId'
    | '/farmer/products/new'
    | '/farmer/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/buyer/cart'
    | '/buyer/dashboard'
    | '/buyer/orders'
    | '/farmer/dashboard'
    | '/marketplace/$productId'
    | '/marketplace'
    | '/api/auth/$'
    | '/farmer/products/$productId'
    | '/farmer/products/new'
    | '/farmer/products'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/buyer/cart'
    | '/buyer/dashboard'
    | '/buyer/orders'
    | '/farmer/dashboard'
    | '/marketplace/$productId'
    | '/marketplace/'
    | '/api/auth/$'
    | '/farmer/products/$productId'
    | '/farmer/products/new'
    | '/farmer/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BuyerCartRoute: typeof BuyerCartRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  BuyerOrdersRoute: typeof BuyerOrdersRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  MarketplaceProductIdRoute: typeof MarketplaceProductIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  FarmerProductsProductIdRoute: typeof FarmerProductsProductIdRoute
  FarmerProductsNewRoute: typeof FarmerProductsNewRoute
  FarmerProductsIndexRoute: typeof FarmerProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/cart': {
      id: '/buyer/cart'
      path: '/buyer/cart'
      fullPath: '/buyer/cart'
      preLoaderRoute: typeof BuyerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/buyer/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/farmer/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$productId': {
      id: '/marketplace/$productId'
      path: '/marketplace/$productId'
      fullPath: '/marketplace/$productId'
      preLoaderRoute: typeof MarketplaceProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/products/': {
      id: '/farmer/products/'
      path: '/farmer/products'
      fullPath: '/farmer/products/'
      preLoaderRoute: typeof FarmerProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/products/$productId': {
      id: '/farmer/products/$productId'
      path: '/farmer/products/$productId'
      fullPath: '/farmer/products/$productId'
      preLoaderRoute: typeof FarmerProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/products/new': {
      id: '/farmer/products/new'
      path: '/farmer/products/new'
      fullPath: '/farmer/products/new'
      preLoaderRoute: typeof FarmerProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BuyerCartRoute: BuyerCartRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  BuyerOrdersRoute: BuyerOrdersRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  MarketplaceProductIdRoute: MarketplaceProductIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  FarmerProductsProductIdRoute: FarmerProductsProductIdRoute,
  FarmerProductsNewRoute: FarmerProductsNewRoute,
  FarmerProductsIndexRoute: FarmerProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
